### ISSUE TITLE
Swapping to blank character-specific keybind profile

### ISSUE THREAD

**Issue by Rhykes** [AcidWeb/RETabBinder#2]
Ever since 8.1, my keybindings are being swapped to a completely blank Character-Specific profile upon log-in. This happened periodically seemingly at random before, but it was extremely rare. It happens almost every time since the patch. I would have to swap back to global keybindings each log-in.

Once I disabled this addon, I have not had it happen once and I have been relogging repeatedly and on different characters to verify that I'm not just suddenly getting lucky.

No lua error is associated with this problem.

**Comment by AcidWeb** [comment]
I can't replicate this issue.

**Comment by AcidWeb** [comment]
It should be fixed in next release.
